---
title: "Vaping – the new go-to drug?"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_bw())
```

## Team members are:
**Name (UNI)**

1. Ying Chen (yc384)
2. Jin Ge (jg4197)
3. Daniela Quigee (dq2147)
4. Hao Sun (hs3163)
5. Siquan Wang (sw3442)
[in alphabetical order]

## Motivation

Vaping, the inhaling of a vapor created by vaping devices like e-cigarettes, was initially regarded as a less harmful substitution for cigarettes. However, vaping still introduces nicotine into the body. The prevalence of lung damage caused by vaping is actually so high that the CDC[[1](https://www.sciencedirect.com/science/article/pii/S2213260019304096?via=ihub)] needed to issue guidance explicitly on it.  As the popularity of vaping grows, concerns about vaping are covered both in academia and in the press[[2](https://health.usnews.com/health-care/for-better/articles/2018-06-13/how-teenage-vaping-puts-structure-in-place-for-heroin-and-cocaine-addiction),[3](https://www.cnn.com/2015/09/04/us/vaping-abuse/index.html)]. A journal article published last week even describes the prevalence of vaping in a "red alert" state[[4](https://link.springer.com/article/10.1057/s41271-019-00193-2)]. In press, vaping is accused of being both a  gateway drug and a new "drug" itself. To provide grounds for potential public health interventions on this "scourge of drug"[[5](https://www.cnn.com/2015/09/04/us/vaping-abuse/index.html)], we will evaluate the current landscape of vaping usage among teenagers and young adults in NYC using pre-collected data and analyze the potential risks of vaping in terms of future substance abuse and mental hygiene condistions.

## Data sources:
Below are some datasets that dive into these topics and we intend on using

1.    National Survey on Drug Use and Health ([NSDUH](<https://www.samhsa.gov/data/all-reports?f[]=field_report_and_document_type:6461&f[]=field_samhsa_survey:6511&f%5B%5D[]=field_report_and_document_type:6461&f%5B%5D[]=field_samhsa_survey:6511&order=desc&sort=field_date_printed_on_report&items_per_page=15&page=0>)) offers the information of multiple drugs.

2.   [YRBSS](https://www.cdc.gov/healthyyouth/data/yrbs/data.htm) Data contains data of the youths' risk behaviors.

3.   [State Tobacco Activities Tracking and Evaluation (State) Sytem](https://nccd.cdc.gov/STATESystem/rdPage.aspx?rdReport=OSH_State.CustomReports&rdAgReset=True&rdShowModes=showResults&rdShowWait=true&rdPaging=Interactive&islMeasure=180EVP) provides the data of NYC tobacco use.

4.   [Youth Risk Behavior Survey](https://a816-healthpsi.nyc.gov/epiquery/YRBS/yrbsIndex.html) contains information of risk behaviors in youths around New York City.


## Intended Final Products
The purpose of this project is to see whether vaping can be regarded as a new go-to drug. We will focus on teenagers and young adults.
We anticipate to create the following products:

* Report
* Webpage
* Screencast
* Dashboard visualizing significant findings

## The planned analyses / visualizations / coding challenges
We will visualize the geographic distribution of vaping and other drugs in New York City. We will analyze how vaping and drug use of other sorts differ with respect to certain characteristics, such as age and sex. We will analyze how drug use/ vaping has developed over recent years. In order to find possible associations with mental illnesses, we will analyze the prevalence and distribution of mental illnesses and compare it with the prevalence and distribution of vaping and other drug uses.

We anticipate challenges when it comes to incorporating multiple data sources and converting them into a tidy format that is easy to use for our analysis.

## Planned Timeline:
* 11.11-11.15: visualizing and doing hypothesis testing
* 11.18-11.23: making website
* 11.26-11.29: improving and completing the final project
* 12.2-12.5: preparing to do presentation

