---
title: "risky_behavior"
author: "Hao Sun"
date: "11/30/2019"
output: html_document
---

```{r setup, include=FALSE}
library("tidyverse")
knitr::opts_chunk$set(echo = TRUE)
```

## Data processing

This section collaped the survey data into stat
```{r dp}
load("./data/nyc_data.RData")
head(df_total,100)

clnames<-c(
  ##Basic demographic
    colnames(df_total)[1:6],colnames(df_total)[8],
    ###Risky behavior,bullied,fighting
           colnames(df_total)[13:32],
    ###Vaping
           colnames(df_total)[41:42],
    ###Danger drug Behavior
           colnames(df_total)[60:61], 
    ###Danger Sex Behavior
          colnames(df_total)[63:68])

clnames

nyc_risky<-df_total%>%select(clnames)

####Fill NA
fill_NA = function(vector){
  #### fill in missing values with "virginica" 
    as.factor(coalesce(as.character(vector),"unknown"))
  }
  
##Do everything across column and merge the output into dataset.
nyc_risky_non<-map_df(nyc_risky,fill_NA)
nyc_risky_non%>%mutate(id = as.numeric(as.character(id)),year = as.numeric(as.character(year)))

nyc_risky_non_stat<-nyc_risky_non%>%select(-"id")%>%pivot_longer(names_to = "question",values_to = "response",cols = 3:36)%>%count(borough,year,question,response)


nyc_risky_non_stat%>%filter(year == 2017, borough == "Bronx",question == c("texting_and_driving","current_vaping"))%>%

ggplot(aes(x=response,y=n))+geom_col()+facet_grid(~question)

nyc_risky_non_stat%>%filter(response == "unknown")%>%group_by(question)%>%summarise(sum(n))
```

```{r}
naperc_df=map_df(df_total,fill_NA)%>%mutate(id = as.numeric(as.character(id)),year = as.numeric(as.character(year)))%>%
  select(-"id")%>%
  pivot_longer(names_to = "question",values_to = "response",cols = 3:ncol(.))%>%
  count(borough,year,question,response)%>%
  filter(response == "unknown")%>%
  group_by(year,question)%>%
  summarise(sum(n))%>%
  left_join(x = . , y = df_total%>%group_by(year)%>%summarise(n()))%>%
  mutate(naperc = `sum(n)`/`n()`)
view(naperc_df)


df_total%>%filter(year == c(2015,2017))%>%group_by(year)%>%summarise(n())
```

