---
title: "NYC Youth"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    css: styles_Dashboard.css
runtime: shiny
---

```{r setup, include=FALSE}
# Loading necessary libraries
library(flexdashboard)
library(shiny)
library(plotly)
library(tidyverse)

# Loading the cleaned data
load("./data/nyc_data.RData")
```


Drug Use
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------
```{r Sidebar_11}
drugs_1 = c("Marijuana", "Alcohol", "Cigarettes", "Vaping", "Smokeless Tobacco",
          "Cigar")
  
selectInput("drugs_1", label = h3("Choose Substance Abuse"),
            choices = as.list(drugs_1), selected = "Marijuana")



years_D = df_total %>% distinct(year) %>% pull()
  
selectInput("years_D", label = h3("Choose year"),
            choices = as.list(years_D), selected = "2017")


boroughs_D = df_total %>% distinct(borough) %>% pull()

selectInput("boroughs_D",label = h3("Select borough"),
            choices = boroughs_D, selected = "Manhattan")

radioButtons(
  "grouping_choice_D", 
  label = h3("Group by"),
  choices = c("nothing", "sex", "age", "race"))
```


Column {.tabset .tabset-fade .tabset-pills}
-----------------------------------------------------------------------

### <span style="color:#69899f"> **Drug Use** </span>

```{r data_11}
renderPlotly({
  df_11 = df_total %>% 
    filter(
      borough == input$boroughs_D,
      year == input$years_D) 
  
  if (input$grouping_choice_D == "nothing")
  {
    if (input$drugs_1 == "Marijuana") {
      df_11 = df_11 %>%
        filter(!(is.na(current_marijuana_use))) %>% 
        count(current_marijuana_use) %>% 
        rename(x = current_marijuana_use)}
    else if (input$drugs_1 == "Alcohol") {
      df_11 = df_11 %>%
        filter(!(is.na(current_alcohol_use))) %>% 
        count(current_alcohol_use) %>% 
        rename(x = current_alcohol_use)}
    else if (input$drugs_1 == "Cigarettes") {
      df_11 = df_11 %>%
        filter(!(is.na(current_cigarette_use))) %>% 
        count(current_cigarette_use) %>% 
        rename(x = current_cigarette_use)}
    else if (input$drugs_1 == "Vaping") {
      df_11 = df_11 %>%
        filter(!(is.na(current_vaping))) %>% 
        count(current_vaping) %>% 
        rename(x = current_vaping)}
    else if (input$drugs_1 == "Smokeless Tobacco") {
      df_11 = df_11 %>%
        filter(!(is.na(current_smokeless_tobacco_use))) %>% 
        count(current_smokeless_tobacco_use) %>% 
        rename(x = current_smokeless_tobacco_use)}
    else if (input$drugs_1 == "Cigar") {
      df_11 = df_11 %>%
        filter(!(is.na(current_cigar_use))) %>% 
        count(current_cigar_use) %>% 
        rename(x = current_cigar_use)}
    
    df_11 = df_11 %>%
      mutate(
          percent = (n / sum(n)),
          percent = percent * 100,
          percent = round(percent, digits = 2))
    
    if (nrow(df_11) > 1)
    {
      df_11 %>% 
      plot_ly(
          x = ~x, 
          y = ~percent, 
          marker = list(color = 'rgb(158,202,225)',
                      line = list(color = 'rgb(8,48,107)',
                                  width = 1.5)),
          type = "bar",
          hovertemplate = "%{y} % <extra></extra>") %>% 
      layout(
        xaxis = list(
          title = ""),
        yaxis = list(
          title = "Percent",
          dtick = 5,
          tick0 = 0,
          tickmode = "linear",
          range = c(0, 100)),
        title = str_c("Percentage currently use ", input$drugs_1," (past 30 days)\n ",input$boroughs_D, " ", input$years_D))
    }
    else{
      text_warning = "No data available"
      x = 1
      y = 1
      
      plot_ly(x = ~x, y = ~y, mode = 'text', text = ~text_warning, textposition = 'middle',
        textfont = list(size = 16)) %>% 
        layout(
          xaxis = list(
            title = ""),
          yaxis = list(
            title = "")
        )
    }
  }
  else if (input$grouping_choice_D == "sex")
  {
    if (input$drugs_1 == "Marijuana") {
      df_11 = df_11 %>%
        filter((!(is.na(current_marijuana_use))) & (!(is.na(sex)))) %>% 
        group_by(sex) %>% 
        count(current_marijuana_use) %>% 
        rename(x = current_marijuana_use)}
    else if (input$drugs_1 == "Alcohol") {
      df_11 = df_11 %>%
        filter((!(is.na(current_alcohol_use))) & (!(is.na(sex)))) %>% 
        group_by(sex) %>% 
        count(current_alcohol_use) %>% 
        rename(x = current_alcohol_use)}
    else if (input$drugs_1 == "Cigarettes") {
      df_11 = df_11 %>%
        filter((!(is.na(current_cigarette_use))) & (!(is.na(sex)))) %>% 
        group_by(sex) %>% 
        count(current_cigarette_use) %>% 
        rename(x = current_cigarette_use)}
    else if (input$drugs_1 == "Vaping") {
      df_11 = df_11 %>%
        filter((!(is.na(current_vaping))) & (!(is.na(sex)))) %>% 
        group_by(sex) %>% 
        count(current_vaping) %>% 
        rename(x = current_vaping)}
    else if (input$drugs_1 == "Smokeless Tobacco") {
      df_11 = df_11 %>%
        filter((!(is.na(current_smokeless_tobacco_use))) & (!(is.na(sex)))) %>% 
        group_by(sex) %>% 
        count(current_smokeless_tobacco_use) %>% 
        rename(x = current_smokeless_tobacco_use)}
    else if (input$drugs_1 == "Cigar") {
      df_11 = df_11 %>%
        filter((!(is.na(current_cigar_use))) & (!(is.na(sex)))) %>% 
        group_by(sex) %>% 
        count(current_cigar_use) %>% 
        rename(x = current_cigar_use)}
    
    df_11 = df_11 %>%
      mutate(
          percent = (n / sum(n)),
          percent = percent * 100,
          percent = round(percent, digits = 2))
    
    if (nrow(df_11) > 1)
    {
      df_11 %>% 
      plot_ly(
          x = ~x, 
          y = ~percent, 
          color = ~sex,
          type = "bar",
          hovertemplate = "%{y} % <extra></extra>") %>% 
      layout(
        xaxis = list(
          title = ""),
        yaxis = list(
          title = "Percent",
          dtick = 5,
          tick0 = 0,
          tickmode = "linear",
          range = c(0, 100)),
        title = str_c("Percentage currently use ", input$drugs_1," (past 30 days)\n ",input$boroughs_D, " ", input$years_D))
    }
    else{
      text_warning = "No data available"
      x = 1
      y = 1
      
      plot_ly(x = ~x, y = ~y, mode = 'text', text = ~text_warning, textposition = 'middle',
        textfont = list(size = 16)) %>% 
        layout(
          xaxis = list(
            title = ""),
          yaxis = list(
            title = "")
        )
    }
  }
  else if (input$grouping_choice_D == "age")
  {
    if (input$drugs_1 == "Marijuana") {
      df_11 = df_11 %>%
        filter((!(is.na(current_marijuana_use))) & (!(is.na(age)))) %>% 
        group_by(age) %>% 
        count(current_marijuana_use) %>% 
        rename(x = current_marijuana_use)}
    else if (input$drugs_1 == "Alcohol") {
      df_11 = df_11 %>%
        filter((!(is.na(current_alcohol_use))) & (!(is.na(age)))) %>% 
        group_by(age) %>% 
        count(current_alcohol_use) %>% 
        rename(x = current_alcohol_use)}
    else if (input$drugs_1 == "Cigarettes") {
      df_11 = df_11 %>%
        filter((!(is.na(current_cigarette_use))) & (!(is.na(age)))) %>% 
        group_by(age) %>% 
        count(current_cigarette_use) %>% 
        rename(x = current_cigarette_use)}
    else if (input$drugs_1 == "Vaping") {
      df_11 = df_11 %>%
        filter((!(is.na(current_vaping))) & (!(is.na(age)))) %>% 
        group_by(age) %>% 
        count(current_vaping) %>% 
        rename(x = current_vaping)}
    else if (input$drugs_1 == "Smokeless Tobacco") {
      df_11 = df_11 %>%
        filter((!(is.na(current_smokeless_tobacco_use))) & (!(is.na(age)))) %>% 
        group_by(age) %>% 
        count(current_smokeless_tobacco_use) %>% 
        rename(x = current_smokeless_tobacco_use)}
    else if (input$drugs_1 == "Cigar") {
      df_11 = df_11 %>%
        filter((!(is.na(current_cigar_use))) & (!(is.na(age)))) %>% 
        group_by(age) %>% 
        count(current_cigar_use) %>% 
        rename(x = current_cigar_use)}
    
    df_11 = df_11 %>%
      mutate(
          percent = (n / sum(n)),
          percent = percent * 100,
          percent = round(percent, digits = 2))
    
    if (nrow(df_11) > 1)
    {
      df_11 %>% 
      plot_ly(
          x = ~x, 
          y = ~percent, 
          color = ~age,
          type = "bar",
          hovertemplate = "%{y} % <extra></extra>") %>% 
      layout(
        xaxis = list(
          title = ""),
        yaxis = list(
          title = "Percent",
          dtick = 5,
          tick0 = 0,
          tickmode = "linear",
          range = c(0, 100)),
        title = str_c("Percentage currently use ", input$drugs_1," (past 30 days)\n",input$boroughs_D, " ", input$years_D))
    }
    else{
      text_warning = "No data available"
      x = 1
      y = 1
      
      plot_ly(x = ~x, y = ~y, mode = 'text', text = ~text_warning, textposition = 'middle',
        textfont = list(size = 16)) %>% 
        layout(
          xaxis = list(
            title = ""),
          yaxis = list(
            title = "")
        )
    }
  }
  else if (input$grouping_choice_D == "race")
  {
    if (input$drugs_1 == "Marijuana") {
      df_11 = df_11 %>%
        filter((!(is.na(current_marijuana_use))) & (!(is.na(race7)))) %>% 
        group_by(race7) %>% 
        count(current_marijuana_use) %>% 
        rename(x = current_marijuana_use)}
    else if (input$drugs_1 == "Alcohol") {
      df_11 = df_11 %>%
        filter((!(is.na(current_alcohol_use))) & (!(is.na(race7)))) %>% 
        group_by(race7) %>% 
        count(current_alcohol_use) %>% 
        rename(x = current_alcohol_use)}
    else if (input$drugs_1 == "Cigarettes") {
      df_11 = df_11 %>%
        filter((!(is.na(current_cigarette_use))) & (!(is.na(race7)))) %>% 
        group_by(race7) %>% 
        count(current_cigarette_use) %>% 
        rename(x = current_cigarette_use)}
    else if (input$drugs_1 == "Vaping") {
      df_11 = df_11 %>%
        filter((!(is.na(current_vaping))) & (!(is.na(race7)))) %>% 
        group_by(race7) %>% 
        count(current_vaping) %>% 
        rename(x = current_vaping)}
    else if (input$drugs_1 == "Smokeless Tobacco") {
      df_11 = df_11 %>%
        filter((!(is.na(current_smokeless_tobacco_use))) & (!(is.na(race7)))) %>% 
        group_by(race7) %>% 
        count(current_smokeless_tobacco_use) %>% 
        rename(x = current_smokeless_tobacco_use)}
    else if (input$drugs_1 == "Cigar") {
      df_11 = df_11 %>%
        filter((!(is.na(current_cigar_use))) & (!(is.na(race7)))) %>% 
        group_by(race7) %>% 
        count(current_cigar_use) %>% 
        rename(x = current_cigar_use)}
    
    df_11 = df_11 %>%
      mutate(
          percent = (n / sum(n)),
          percent = percent * 100,
          percent = round(percent, digits = 2))
    
    if (nrow(df_11) > 1)
    {
      df_11 %>% 
      plot_ly(
          x = ~x, 
          y = ~percent,
          color = ~race7,
          type = "bar",
          hovertemplate = "%{y} % <extra></extra>") %>% 
      layout(
        xaxis = list(
          title = ""),
        yaxis = list(
          title = "Percent",
          dtick = 5,
          tick0 = 0,
          tickmode = "linear",
          range = c(0, 100)),
        title = str_c("Percentage currently use ", input$drugs_1," (past 30 days)\n",input$boroughs_D, " ", input$years_D))
    }
    else{
      text_warning = "No data available"
      x = 1
      y = 1
      
      plot_ly(x = ~x, y = ~y, mode = 'text', text = ~text_warning, textposition = 'middle',
        textfont = list(size = 16)) %>% 
        layout(
          xaxis = list(
            title = ""),
          yaxis = list(
            title = "")
        )
    }
  }
})
```

### <span style="color:#69899f"> **Description** </span>




Drug Use over Time
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------
```{r Sidebar_12}
drugs_2 = c("Marijuana", "Alcohol", "Cigarettes", "Vaping", "Smokeless Tobacco",
          "Cigar")
  
selectInput("drugs_2", label = h3("Choose Substance Abuse"),
            choices = as.list(drugs_2), selected = "Marijuana")
```

Column {.tabset}
-----------------------------------------------------------------------

### <span style="color:#69899f"> **Drug Use** </span>

```{r data_12}
renderPlotly({
  if (input$drugs_2 == "Marijuana") {
    df_12 = df_total %>% 
      filter(!(is.na(current_marijuana_use))) %>%
      group_by(year, borough) %>% 
      count(current_marijuana_use) %>% 
      mutate(
        percent = (n / sum(n)),
        percent = percent * 100,
        percent = round(percent, digits = 2)) %>% 
      filter(current_marijuana_use == "Yes")
  }
  else if (input$drugs_2 == "Alcohol") {
    df_12 = df_total %>% 
      filter(!(is.na(current_alcohol_use))) %>% 
      group_by(year, borough) %>% 
      count(current_alcohol_use) %>% 
      mutate(
        percent = (n / sum(n)),
        percent = percent * 100,
        percent = round(percent, digits = 2)) %>% 
      filter(current_alcohol_use == "Yes")
  }
  else if (input$drugs_2 == "Cigarettes") {
    df_12 = df_total %>% 
      filter(!(is.na(current_cigarette_use))) %>% 
      group_by(year, borough) %>% 
      count(current_cigarette_use) %>% 
      mutate(
        percent = (n / sum(n)),
        percent = percent * 100,
        percent = round(percent, digits = 2)) %>% 
      filter(current_cigarette_use == "Yes")
  }
  else if (input$drugs_2 == "Vaping") {
    df_12 = df_total %>% 
      filter(!(is.na(current_vaping))) %>% 
      group_by(year, borough) %>% 
      count(current_vaping) %>% 
      mutate(
        percent = (n / sum(n)),
        percent = percent * 100,
        percent = round(percent, digits = 2)) %>% 
      filter(current_vaping == "Yes")
  }
  else if (input$drugs_2 == "Smokeless Tobacco") {
    df_12 = df_total %>% 
      filter(!(is.na(current_smokeless_tobacco_use))) %>% 
      group_by(year, borough) %>% 
      count(current_smokeless_tobacco_use) %>% 
      mutate(
        percent = (n / sum(n)),
        percent = percent * 100,
        percent = round(percent, digits = 2)) %>% 
      filter(current_smokeless_tobacco_use == "Yes")
  }
  else if (input$drugs_2 == "Cigar") {
    df_12 = df_total %>% 
      filter(!(is.na(current_cigar_use))) %>% 
      group_by(year, borough) %>% 
      count(current_cigar_use) %>% 
      mutate(
        percent = (n / sum(n)),
        percent = percent * 100,
        percent = round(percent, digits = 2)) %>% 
      filter(current_cigar_use == "Yes")
  }
  
  

  df_12 %>% 
      plot_ly(
        x = ~year,
        y = ~percent,
        color = ~borough,
        alpha = 0.7,
        line = list( width = 3, dash = 'dash'),
        hovertemplate = "Year: %{x}\n%{y} % ") %>% 
      layout( 
          xaxis = list(
            title = "Year",
            dtick = 2,
            tick0 = 2003,
            tickmode = "linear",
            range = c(2001, 2019)),
          yaxis = list(
            title = "Percent",
            dtick = 5,
            tick0 = 0,
            tickmode = "linear",
            range = c(0, 50)),
          title = str_c("Percentage currently use ", input$drugs_2, " (past 30 days) over time"))
})
```

### <span style="color:#69899f"> **Description** </span>



Mental Health by Demographics
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------
```{r Sidebar_21}
mental_health_1 = c("feel sad or hopeless", "attempted suicide", "injured during attempted suicide")
  
selectInput("mental_health_1", label = h3("Choose Mental Health"),
            choices = as.list(mental_health_1), selected = "Felt Sad")



years_M = df_total %>% distinct(year) %>% pull()
  
selectInput("years_M", label = h3("Choose year"),
            choices = as.list(years_M), selected = "2017")


boroughs_M = df_total %>% distinct(borough) %>% pull()

selectInput("boroughs_M",label = h3("Select borough"),
            choices = boroughs_M, selected = "Manhattan")

radioButtons(
  "grouping_choice_M", 
  label = h3("Group by"),
  choices = c("nothing", "sex", "age", "race"))
```

Column {.tabset}
-----------------------------------------------------------------------

### <span style="color:#69899f"> **Mental Health** </span>

```{r data_21}
renderPlotly({
  df_21 = df_total %>% 
    filter(
      borough == input$boroughs_M,
      year == input$years_M) 
  
  if (input$grouping_choice_M == "nothing")
  {
    if (input$mental_health_1 == "feel sad or hopeless") {
      df_21 = df_21 %>%
        filter(!(is.na(sad_hopeless))) %>% 
        count(sad_hopeless) %>% 
        rename(x = sad_hopeless)}
    else if (input$mental_health_1 == "attempted suicide") {
      df_21 = df_21 %>%
        filter(!(is.na(attempted_suicide))) %>% 
        count(attempted_suicide) %>% 
        rename(x = attempted_suicide)}
    else if (input$mental_health_1 == "injured during attempted suicide") {
      df_21 = df_21 %>%
        filter(!(is.na(injurious_suicide_attempt))) %>% 
        count(injurious_suicide_attempt) %>% 
        rename(x = injurious_suicide_attempt)}
    
  df_21 = df_21 %>%
      mutate(
          percent = (n / sum(n)),
          percent = percent * 100,
          percent = round(percent, digits = 2))
  
   if (nrow(df_21) > 1)
    {
      df_21 %>% 
      plot_ly(
          x = ~x, 
          y = ~percent, 
          marker = list(color = 'rgb(158,202,225)',
                      line = list(color = 'rgb(8,48,107)',
                                  width = 1.5)),
          type = "bar",
          hovertemplate = "%{y} % <extra></extra>") %>% 
      layout(
        xaxis = list(
          title = ""),
        yaxis = list(
          title = "Percent",
          dtick = 5,
          tick0 = 0,
          tickmode = "linear",
          range = c(0, 100)),
        title = str_c("Percentage ", input$mental_health_1," (past 12 months)\n ",input$boroughs_M, " ", input$years_M))
    }
    else{
      text_warning = "No data available"
      x = 1
      y = 1
      
      plot_ly(x = ~x, y = ~y, mode = 'text', text = ~text_warning, textposition = 'middle',
        textfont = list(size = 16)) %>% 
        layout(
          xaxis = list(
            title = ""),
          yaxis = list(
            title = "")
        )
    }
  }

  
  else if (input$grouping_choice_M == "sex")
  {
    if (input$mental_health_1 == "feel sad or hopeless") {
      df_21 = df_21 %>%
        filter((!(is.na(sad_hopeless))) & (!(is.na(sex)))) %>% 
        group_by(sex) %>% 
        count(sad_hopeless) %>% 
        rename(x = sad_hopeless)}
    else if (input$mental_health_1 == "attempted suicide") {
      df_21 = df_21 %>%
        filter((!(is.na(attempted_suicide))) & (!(is.na(sex)))) %>% 
        group_by(sex) %>% 
        count(attempted_suicide) %>% 
        rename(x = attempted_suicide)}
    else if (input$mental_health_1 == "injured during attempted suicide") {
      df_21 = df_21 %>%
        filter((!(is.na(injurious_suicide_attempt))) & (!(is.na(sex)))) %>% 
        group_by(sex) %>% 
        count(injurious_suicide_attempt) %>% 
        rename(x = injurious_suicide_attempt)}
    
  df_21 = df_21 %>%
      mutate(
          percent = (n / sum(n)),
          percent = percent * 100,
          percent = round(percent, digits = 2))
  
   if (nrow(df_21) > 1)
    {
      df_21 %>% 
      plot_ly(
          x = ~x, 
          y = ~percent, 
          color = ~sex,
          type = "bar",
          hovertemplate = "%{y} % <extra></extra>") %>% 
      layout(
        xaxis = list(
          title = ""),
        yaxis = list(
          title = "Percent",
          dtick = 5,
          tick0 = 0,
          tickmode = "linear",
          range = c(0, 100)),
        title = str_c("Percentage ", input$mental_health_1," (past 12 months)\n ",input$boroughs_M, " ", input$years_M))
    }
    else{
      text_warning = "No data available"
      x = 1
      y = 1
      
      plot_ly(x = ~x, y = ~y, mode = 'text', text = ~text_warning, textposition = 'middle',
        textfont = list(size = 16)) %>% 
        layout(
          xaxis = list(
            title = ""),
          yaxis = list(
            title = "")
        )
    }
  }
  
  
  else if (input$grouping_choice_M == "age")
  {
    if (input$mental_health_1 == "feel sad or hopeless") {
      df_21 = df_21 %>%
        filter((!(is.na(sad_hopeless))) & (!(is.na(age)))) %>% 
        group_by(age) %>% 
        count(sad_hopeless) %>% 
        rename(x = sad_hopeless)}
    else if (input$mental_health_1 == "attempted suicide") {
      df_21 = df_21 %>%
        filter((!(is.na(attempted_suicide))) & (!(is.na(age)))) %>% 
        group_by(age) %>% 
        count(attempted_suicide) %>% 
        rename(x = attempted_suicide)}
    else if (input$mental_health_1 == "injured during attempted suicide") {
      df_21 = df_21 %>%
        filter((!(is.na(injurious_suicide_attempt))) & (!(is.na(age)))) %>% 
        group_by(age) %>% 
        count(injurious_suicide_attempt) %>% 
        rename(x = injurious_suicide_attempt)}
    
  df_21 = df_21 %>%
      mutate(
          percent = (n / sum(n)),
          percent = percent * 100,
          percent = round(percent, digits = 2))
  
   if (nrow(df_21) > 1)
    {
      df_21 %>% 
      plot_ly(
          x = ~x, 
          y = ~percent, 
          color = ~age,
          type = "bar",
          hovertemplate = "%{y} % <extra></extra>") %>% 
      layout(
        xaxis = list(
          title = ""),
        yaxis = list(
          title = "Percent",
          dtick = 5,
          tick0 = 0,
          tickmode = "linear",
          range = c(0, 100)),
        title = str_c("Percentage ", input$mental_health_1," (past 12 months)\n ",input$boroughs_M, " ", input$years_M))
    }
    else{
      text_warning = "No data available"
      x = 1
      y = 1
      
      plot_ly(x = ~x, y = ~y, mode = 'text', text = ~text_warning, textposition = 'middle',
        textfont = list(size = 16)) %>% 
        layout(
          xaxis = list(
            title = ""),
          yaxis = list(
            title = "")
        )
    }
  }
  
  
  else if (input$grouping_choice_M == "race")
  {
    if (input$mental_health_1 == "feel sad or hopeless") {
      df_21 = df_21 %>%
        filter((!(is.na(sad_hopeless))) & (!(is.na(race7)))) %>% 
        group_by(race7) %>% 
        count(sad_hopeless) %>% 
        rename(x = sad_hopeless)}
    else if (input$mental_health_1 == "attempted suicide") {
      df_21 = df_21 %>%
        filter((!(is.na(attempted_suicide))) & (!(is.na(race7)))) %>% 
        group_by(race7) %>% 
        count(attempted_suicide) %>% 
        rename(x = attempted_suicide)}
    else if (input$mental_health_1 == "injured during attempted suicide") {
      df_21 = df_21 %>%
        filter((!(is.na(injurious_suicide_attempt))) & (!(is.na(race7)))) %>% 
        group_by(race7) %>% 
        count(injurious_suicide_attempt) %>% 
        rename(x = injurious_suicide_attempt)}
    
  df_21 = df_21 %>%
      mutate(
          percent = (n / sum(n)),
          percent = percent * 100,
          percent = round(percent, digits = 2))
  
   if (nrow(df_21) > 1)
    {
      df_21 %>% 
      plot_ly(
          x = ~x, 
          y = ~percent, 
          color = ~race7,
          type = "bar",
          hovertemplate = "%{y} % <extra></extra>") %>% 
      layout(
        xaxis = list(
          title = ""),
        yaxis = list(
          title = "Percent",
          dtick = 5,
          tick0 = 0,
          tickmode = "linear",
          range = c(0, 100)),
        title = str_c("Percentage ", input$mental_health_1," (past 12 months)\n ",input$boroughs_M, " ", input$years_M))
    }
    else{
      text_warning = "No data available"
      x = 1
      y = 1
      
      plot_ly(x = ~x, y = ~y, mode = 'text', text = ~text_warning, textposition = 'middle',
        textfont = list(size = 16)) %>% 
        layout(
          xaxis = list(
            title = ""),
          yaxis = list(
            title = "")
        )
    }
  }
  
})  
```

### <span style="color:#69899f"> **Description** </span>



Mental Health over Time
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------
```{r Sidebar_22}
mental_health_2 = c("feel sad or hopeless", "attempted suicide", "injured during attempted suicide")
  
selectInput("mental_health_2", label = h3("Choose Mental Health"),
            choices = as.list(mental_health_2), selected = "Felt Sad")
```

Column {.tabset}
-----------------------------------------------------------------------

### Drug Use

```{r data_22}
renderPlotly({
  
  if (input$mental_health_2 == "feel sad or hopeless") {
    df_22 = df_total %>%
      filter(!(is.na(sad_hopeless))) %>% 
      group_by(year, borough) %>% 
      count(sad_hopeless) %>% 
      mutate(
        percent = (n / sum(n)),
        percent = percent * 100,
        percent = round(percent, digits = 2)) %>% 
      filter(sad_hopeless == "Yes")
  }
  else if (input$mental_health_2 == "attempted suicide") {
    df_22 = df_total %>%
      filter(!(is.na(attempted_suicide))) %>% 
      group_by(year, borough) %>% 
      count(attempted_suicide) %>% 
      mutate(
        percent = (n / sum(n)),
        percent = percent * 100,
        percent = round(percent, digits = 2)) %>% 
      filter(attempted_suicide == "Yes")
  }
  else if (input$mental_health_2 == "injured during attempted suicide") {
    df_22 = df_total %>%
      filter(!(is.na(injurious_suicide_attempt))) %>% 
      group_by(year, borough) %>% 
      count(injurious_suicide_attempt) %>% 
      mutate(
        percent = (n / sum(n)),
        percent = percent * 100,
        percent = round(percent, digits = 2)) %>% 
      filter(injurious_suicide_attempt == "Yes")
  }

  df_22 %>% 
      plot_ly(
        x = ~year,
        y = ~percent,
        color = ~borough,
        alpha = 0.7,
        line = list( width = 3, dash = 'dash'),
        hovertemplate = "Year: %{x}\n%{y} % ") %>% 
      layout( 
          xaxis = list(
            title = "Year",
            dtick = 2,
            tick0 = 2003,
            tickmode = "linear",
            range = c(2001, 2019)),
          yaxis = list(
            title = "Percent",
            dtick = 5,
            tick0 = 0,
            tickmode = "linear",
            range = c(0, 40)),
         title = str_c("Percentage ", input$mental_health_1," (past 12 months)\n ", input$years_M))
})
```

### <span style="color:#69899f"> **Decription** </span>

